### ISSUE TITLE
Unfortunately, lua-intellisense does not support your operating system or cpu architecture.

### ISSUE THREAD

**Issue by macjabeth** [Mettra/lua-intellisense#1]
I'm running on Windows 10 Home 64-bit and x64-based processor.

**Comment by Mettra** [comment]
Should be fixed now, issue was forming from the new shell version of vscode 1.6

**Comment by macjabeth** [comment]
Cheers! I'll check it out once I'm back on a computer.

**Comment by macjabeth** [comment]
Looks like it's working now.
